# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### STUDENT: João Avanzini
###### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202305

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [2]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[-0.37  3.03  1.67 -0.73 -6.  ]
 [ 0.35  1.89  0.87 -1.12  3.98]
 [-0.5  -1.9   1.49  0.75 -1.04]]
 
[[ 0.76  1.82 -0.31 -0.32]
 [-1.9   2.27 -0.17 -1.46]
 [ 2.96 -1.31  0.09 -0.05]
 [-7.53 -1.55  0.8  -2.37]
 [-1.31  1.62 -0.09 -1.38]
 [ 2.69  2.21 -0.69  2.38]
 [ 2.97 -1.4  -0.07  1.99]]


# Using pytorch

In [3]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[ 0.3800, -3.1300,  0.5100,  0.4000, -0.8000,  0.9300, -0.8000],
        [ 1.3200, -2.8400, -0.2900,  0.9300, -1.1900, -0.2400,  1.3400],
        [ 0.1600,  0.1600, -0.1200, -0.3500,  1.2200, -1.8700,  1.7900]],
       dtype=torch.float64)
 
tensor([[ 0.3800, -3.1300,  0.5100,  0.4000, -0.8000,  0.9300, -0.8000],
        [ 1.3200, -2.8400, -0.2900,  0.9300, -1.1900, -0.2400,  1.3400],
        [ 0.1600,  0.1600, -0.1200, -0.3500,  1.2200, -1.8700,  1.7900]])
